# -*- coding: utf-8 -*-
"""50465129_indexer_solr_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bx8bVBIFWDUihz2kQUXUV8Wg5ARB6pfF

# Pysolr Demo

This demo is tailored to provide an introduction to [pysolr](https://pypi.org/project/pysolr/) library, demonstrating how it can manage and optimize your Solr setup, using Python scripts.
"""

!pip install pysolr

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

"""### Installing and Importing Necessary Libraries

"""

import os
import pysolr
import requests
import pandas as pd
import pickle

CORE_NAME = "IRP3"
VM_IP = "34.125.63.64"

"""### Defining Functions and Classes"""

#manually ran these in the vm instance
# def delete_core(core=CORE_NAME):
#     print(os.system('sudo su - solr -c "/opt/solr/bin/solr delete -c {core}"'.format(core=core)))


# def create_core(core=CORE_NAME):
#     print(os.system(
#         'sudo su - solr -c "/opt/solr/bin/solr create -c {core} -n data_driven_schema_configs"'.format(core=core)))

class Indexer:
    def __init__(self):
        self.solr_url = f'http://{VM_IP}:8983/solr/'
        self.connection = pysolr.Solr(self.solr_url + CORE_NAME, always_commit=True, timeout=5000000)

    def do_initial_setup(self):
        delete_core()
        create_core()

    def create_documents(self, docs):
        print(self.connection.add(docs))
    #Adding the needed fields.
    def add_fields(self):
        data = {
            "add-field": [
               {
                    "name": "url",
                    "type": "string",
                    "indexed": True,
                    "multiValued": False
                },
                {
                    "name": "title",
                    "type": "string",
                    "multiValued": False
                },
                {
                    "name": "summary",
                    "type": "text_en",
                    "multiValued": False
                },
                {
                    "name": "revision_id",
                    "type": "string",
                    "multiValued": False
                },
                {
                    "name": "topic",
                    "type": "string",
                    "multiValued": False
                },
            ]
        }

        print(requests.post(self.solr_url + CORE_NAME + "/schema", json=data).json())

"""### Generating a sample dataset for indexing in SOLR"""

!pwd

import pandas as pd
df= pd.read_excel('/content/drive/My Drive/main_scraped_excel.xlsx')
df.shape

"""### Indexing the sample data on our SOLR using the Indexer class defined above"""

# Setting up the core and adding the fields
i = Indexer()
# i.do_initial_setup()

i.add_fields()

# Index the sample dataset
collection = df.to_dict('records')
i.create_documents(collection)

