# -*- coding: utf-8 -*-
"""project_3 _scrapper_50465129 _wiki_scraping_code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kv0m96MjjJrSg7bYdWfRtYzOy2OvdIPZ

### Installing and Importing Necessary Libraries
"""

!pip install wikipedia

import csv
import wikipedia
from wikipedia.exceptions import DisambiguationError
import re

# Creating the list of main topics and it's corresponding sub_topic.
topics = {
"Health": [
        "common diseases", "global health statistics", "mental health trends",
        "Pandemics and outbreaks", "Healthcare access and disparities",
        "Vaccination rates", "Aging population trends",
        "Nutrition and dietary trends", "Healthcare expenditure and financing",
        "Emerging diseases and infections", "Health technology innovations",
        "Maternal and child health indicators", "Leading causes of mortality",
        "Healthcare infrastructure development", "Health-related research advancements",
        "Chronic illnesses prevalence", "Rare diseases research",
        "Alternative medicine trends", "Genetic disorders analysis",
        "Telemedicine advancements", "Healthcare workforce trends",
        "Global health policy analysis", "Holistic wellness practices",
        "Healthcare data privacy concerns", "Pharmaceutical industry trends"
    ],
   "Environment": [
        "global warming", "endangered species", "deforestation rates",
        "Renewable energy adoption", "Pollution levels and mitigation efforts",
        "Biodiversity conservation", "Water scarcity and management",
        "Sustainable development goals progress", "Climate change adaptation strategies",
        "Environmental regulations and policies", "Ecosystem restoration projects",
        "Ocean health and conservation", "Air quality indices",
        "Environmental impact assessments", "Urbanization and its effects on the environment",
        "Wildlife conservation efforts", "Land use and habitat loss",
        "Green technologies and innovations", "Natural disaster resilience",
        "Environmental justice initiatives", "Carbon footprint reduction",
        "Ecotourism trends", "Waste management strategies",
        "Renewable energy investments", "Green infrastructure developments"
    ],
  "Technology": [
        "emerging technologies", "AI advancements", "cybersecurity trends",
        "Robotics and automation trends", "Internet of Things (IoT) innovations",
        "Augmented and virtual reality advancements", "Quantum computing developments",
        "Data privacy concerns", "Biotechnology breakthroughs",
        "5G technology adoption", "Tech industry mergers and acquisitions",
         "Tech startup ecosystem", "Cloud computing growth", "Ethical considerations in technology development",
        "Smart city technologies", "Blockchain innovations",
        "Digital transformation trends", "Health tech innovations",
        "Space technology advancements", "Tech education and skills development",
        "Inclusive technology design", "Regulatory technology trends",
        "Tech-enabled sustainability initiatives", "Human-computer interaction trends"
    ],
  "Economy": ["stock market performance", "job markets", "cryptocurrency trends",
    "Inflation and monetary policies", "Trade and tariff impacts",
    "Economic inequality and poverty rates", "Consumer spending trends",
    "Small business landscape", "Unemployment rates",
    "Economic growth forecasts", "Economic impacts of global events",
    "Cryptocurrency regulations", "Banking and financial sector trends",
    "Real estate market trends", "Economic resilience and recovery strategies",
    "Global trade agreements", "Fiscal stimulus measures",
    "Entrepreneurship and startups", "Labor market dynamics",
    "Regional economic disparities", "Monetary policy adjustments",
    "Commodity market trends", "Income distribution analysis",
    "Economic effects of technological disruptions", "Government debt and deficits"],
"Entertainment": [
    "music industry", "popular cultural events", "streaming platforms",
    "Movie industry trends", "Television show analysis",
    "Gaming industry updates", "Celebrity culture trends",
    "Online content consumption patterns", "Live events and performances",
    "Entertainment technology innovations", "Fan engagement trends",
    "Content creation and distribution strategies", "Art and creative industries",
    "Digital media evolution", "Entertainment marketing trends",
    "Influence of social media on entertainment", "Virtual reality experiences",
    "Impact of piracy on entertainment industry", "Niche content and fandoms",
    "Emerging trends in animation and CGI", "Interactive entertainment experiences",
    "Inclusivity and diversity in entertainment", "Evolving storytelling techniques",
    "Streaming service competition", "Celebrity endorsements and collaborations"
],

"Sports": [
    "major sporting events", "sports analytics",
    "Athlete performance analysis", "Global sports tournaments",
    "Fantasy sports trends", "Sports industry economics",
    "E-sports growth", "Athlete health and fitness trends",
    "Sports broadcasting developments", "Fan engagement strategies",
    "Team and player statistics", "Sports technology advancements",
    "Sports betting trends", "Youth and amateur sports trends",
    "Sports sponsorships and endorsements",
    "Sports psychology and mental health", "Gender equality in sports",
    "Olympic Games analysis", "Youth development programs in sports",
    "Adaptive and para sports", "Trends in sports equipment",
    "Environmental impact of sports events", "Athlete activism in sports",
    "Media's influence on sports narratives", "Evolution of sports rules and regulations"
],

"Politics": [
    "elections", "public policy analysis", "international relations",
    "Political party dynamics", "Government policy reforms",
    "Global geopolitical trends", "Political campaign strategies",
    "Diplomatic relations and treaties", "Public opinion analysis",
    "Legislative developments", "Political ideology shifts",
    "International conflict analysis", "Human rights issues",
    "Political corruption investigations", "Demographic impact on politics",
    "Social movements and activism", "Political polarization trends",
    "Media's role in politics", "Political representation and diversity",
    "Government transparency initiatives", "Youth involvement in politics",
    "Civic engagement and voter turnout", "Religious influence on politics",
    "Political propaganda and misinformation", "Public trust in political institutions"
],

  "Education": [
    "literacy rates", "online education trends", "student loan data",
    "Education system reforms", "E-learning platforms and tools",
    "Education funding and resources", "Educational technology advancements",
    "Global education inequality", "Teaching methodologies and trends",
    "Higher education accessibility", "Digital learning trends",
    "Education policy evaluations", "Remote learning impact analysis",
    "Skills gap analysis", "Educational equity and inclusivity",
    "Education quality assessment metrics", "Lifelong learning trends",
    "Special education and inclusivity programs", "Global student mobility trends",
    "Vocational and technical education advancements", "Curriculum development and adaptation",
    "Education technology ethics and governance", "Gender disparity in education",
    "Early childhood education initiatives", "Hybrid learning models"
  ],

   "Travel": [
    "top tourist destinations", "airline industry data", "travel trends",
    "Travel accommodation trends", "Global travel insights",
    "Travel safety and security measures", "Tourism industry disruptions",
    "Sustainable travel initiatives", "Travel booking and reservations",
    "Destination marketing strategies", "Transportation infrastructure updates",
    "Business travel trends", "Adventure travel preferences",
    "Cultural and heritage tourism", "Solo travel trends",
    "Sustainable tourism practices", "Travel behavior analysis post-pandemic",
    "Medical and wellness tourism trends", "Eco-friendly accommodations",
    "Destination branding strategies", "Travel insurance and risk management",
    "Digital nomadism trends", "Space tourism developments",
    "Impact of social media on travel decisions", "Cultural immersion experiences"
],

"Food": [
    "crop yield statistics", "global hunger and food security", "food production trends",
    "Agricultural technology advancements", "Dietary consumption patterns",
    "Sustainable farming practices", "Food supply chain analysis",
    "Organic and local food trends", "Food waste management strategies",
    "Food industry regulations", "Nutritional health trends",
    "Cuisine popularity and trends", "Food innovation and startups",
    "GMO usage and controversies", "Health-conscious food choices",
    "Regional and indigenous cuisines preservation", "Plant-based food market trends",
    "Agritourism and farm-to-table experiences", "Food certification and labeling regulations",
    "Edible insect consumption trends", "Urban farming and rooftop gardens",
    "Dietary shifts and cultural influences", "Alternative protein sources",
    "Personalized nutrition trends", "Food and beverage sustainability certifications"
],

}


# Create a new csv file for the scraped data
csv_filename = "scraped_data.csv"
csv_file = open(csv_filename, mode='w', newline='', encoding='utf-8')
csv_writer = csv.writer(csv_file)

# Intialize the contents of csv header.
csv_writer.writerow(["URL", "Title", "Summary", "Revision ID", "Topic Name", "Main Topic"])

# we use the below fuction to scrape individual topics using their sub_topic.
def scrape_docs(main_topic, sub_topic=None, maximum_total_docs=5000, maximum_subtopic_docs=350):
    # Intializing a set to remove duplicate documents for the present topic.
    uniquedocs = set()
    totaldocs = 0

    #Iterating through all the results of a subtopic until we reach 500 documents.
    while totaldocs < maximum_total_docs and sub_topic:
      #Defining try and catch blocks to handle disambiguation errors.
        try:
            #using default search function to fetch the documents of a subtopic
            search_res = wikipedia.search(sub_topic[0], results=350)
            print(f"No.of search results for {sub_topic[0]}: {len(search_res)}")

            # Getting the needed content from the search results
            for result in search_res:
                if totaldocs >= maximum_total_docs:
                    break
                # Document uniqueness checker
                if result not in uniquedocs:
                    try:
                        # pre-process the scraped content summary.
                        content = wikipedia.page(result, auto_suggest=False)
                        # filtering out less length summary docs and non-alphanumeric characters.
                        summary = re.sub(r'[^a-zA-Z0-9\s]', '', content.summary)
                        if len(summary) >= 200:
                            # add the filtered doc to the list of docs.
                            uniquedocs.add(result)
                            totaldocs += 1
                            print(f"Scraped {totaldocs} docs from {sub_topic[0]}: {result}")
                            # add the content to the csv file.
                            csv_writer.writerow([content.url, content.title, summary, content.revision_id, sub_topic[0], main_topic])
                    except wikipedia.exceptions.DisambiguationError as e:
                        # in case an error occurs print the error msg.
                        print(f"DisambiguationError for {result}: {e.options}")
            #pop the subtopic after processing.
            sub_topic.pop(0)
        except wikipedia.exceptions.DisambiguationError as e:
            # handling errors that may occurs for the topic.
            print(f"DisambiguationError for {sub_topic[0]}: {e.options}")
            # pop the subtopic which cannot be further iterated for search results
            sub_topic.pop(0)

# Iterate through the list of topics and their respective sub_topic.
for main_topic, subtopic_list in topics.items():
    scrape_docs(main_topic, sub_topic=subtopic_list, maximum_total_docs=5000, maximum_subtopic_docs=350)

# CSV file close
csv_file.close()

#Connect to your google drive
from google.colab import drive
drive.mount('/content/drive')

#Upload the created csv to the mentioned drive location
import shutil
source_path = 'scraped_data.csv'
destination_path = '/content/drive/My Drive/scraped_data_economy.csv'
shutil.copy(source_path, destination_path)
import os
os.path.exists(destination_path)